In [23]:
        import numpy as np
        import pandas as pd
        import matplotlib as plt
        
        from sklearn.neighbors import KNeighborsClassifier
        from sklearn.ensemble import RandomForestClassifier
        from sklearn.linear_model import LogisticRegression
        from sklearn.model_selection import GridSearchCV
        
        from sklearn.metrics import accuracy_score
        from sklearn.metrics import confusion_matrix
        from sklearn.model_selection import KFold 
        from sklearn.model_selection import cross_val_score
        from sklearn.model_selection import cross_val_predict
        
        import warnings
        warnings.filterwarnings("ignore") 
        from subprocess import check_output

In [24]:
dataset = pd.read_csv(r'C:\Users\suyog\Downloads\station_day.csv')

In [25]:
dataset= dataset.drop(['StationId','Date'],axis=1)

In [26]:
dataset.size

1512490

In [27]:
dataset = dataset.dropna()

In [28]:
        X=dataset.iloc[::-1].values
        y=dataset.iloc[:-1].values

In [46]:
dataset.head(10)

,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
1,81.40,124.50,1.44,20.50,12.08,10.72,0.12,15.24,127.09,0.20,6.50,0.06,184.0,1
2,78.32,129.06,1.26,26.00,14.85,10.28,0.14,26.96,117.44,0.22,7.95,0.08,197.0,1
3,88.76,135.32,6.60,30.85,21.77,12.91,0.11,33.59,111.81,0.29,7.63,0.12,198.0,1
4,64.18,104.09,2.56,28.07,17.01,11.42,0.09,19.00,138.18,0.17,5.02,0.07,188.0,1
5,72.47,114.84,5.23,23.20,16.59,12.25,0.16,10.55,109.74,0.21,4.71,0.08,173.0,1
6,69.80,114.86,4.69,20.17,14.54,10.95,0.12,14.07,118.09,0.16,3.52,0.06,165.0,1
7,73.96,113.56,4.58,19.29,13.97,10.95,0.10,13.90,123.80,0.17,2.85,0.04,191.0,1
8,89.90,140.20,7.71,26.19,19.87,13.12,0.10,19.37,128.73,0.25,2.79,0.07,191.0,1
9,87.14,130.52,0.97,21.31,12.12,14.36,0.15,11.41,114.80,0.23,3.82,0.04,227.0,2
10,84.64,125.00,4.02,26.98,17.58,14.41,0.18,9.84,112.41,0.31,3.53,0.09,168.0,1

In [47]:
        from sklearn.preprocessing import LabelEncoder
        labelencoder = LabelEncoder()
        dataset['AQI_Bucket'] = labelencoder.fit_transform(dataset['AQI_Bucket'])
        dataset.head(10)

,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
1,81.40,124.50,1.44,20.50,12.08,10.72,0.12,15.24,127.09,0.20,6.50,0.06,184.0,1
2,78.32,129.06,1.26,26.00,14.85,10.28,0.14,26.96,117.44,0.22,7.95,0.08,197.0,1
3,88.76,135.32,6.60,30.85,21.77,12.91,0.11,33.59,111.81,0.29,7.63,0.12,198.0,1
4,64.18,104.09,2.56,28.07,17.01,11.42,0.09,19.00,138.18,0.17,5.02,0.07,188.0,1
5,72.47,114.84,5.23,23.20,16.59,12.25,0.16,10.55,109.74,0.21,4.71,0.08,173.0,1
6,69.80,114.86,4.69,20.17,14.54,10.95,0.12,14.07,118.09,0.16,3.52,0.06,165.0,1
7,73.96,113.56,4.58,19.29,13.97,10.95,0.10,13.90,123.80,0.17,2.85,0.04,191.0,1
8,89.90,140.20,7.71,26.19,19.87,13.12,0.10,19.37,128.73,0.25,2.79,0.07,191.0,1
9,87.14,130.52,0.97,21.31,12.12,14.36,0.15,11.41,114.80,0.23,3.82,0.04,227.0,2
10,84.64,125.00,4.02,26.98,17.58,14.41,0.18,9.84,112.41,0.31,3.53,0.09,168.0,1

In [31]:
dataset['AQI_Bucket'].value_counts()

1    4402
3    3730
0    1073
2     610
5     399
4     100
Name: AQI_Bucket, dtype: int64

In [32]:
dataset.columns

Index(['PM2.5', 'PM10', 'NO', 'NO2', 'NOx', 'NH3', 'CO', 'SO2', 'O3',
       'Benzene', 'Toluene', 'Xylene', 'AQI', 'AQI_Bucket'],
      dtype='object')

In [33]:
         X = dataset[['PM2.5' ,'PM10', 'NO' ,'NO2', 'NOx', 'NH3' ,'CO' ,'SO2' ,'O3',
               'Benzene' ,'Toluene' ,'Xylene']]
         X

,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene
1,81.40,124.50,1.44,20.50,12.08,10.72,0.12,15.24,127.09,0.20,6.50,0.06
2,78.32,129.06,1.26,26.00,14.85,10.28,0.14,26.96,117.44,0.22,7.95,0.08
3,88.76,135.32,6.60,30.85,21.77,12.91,0.11,33.59,111.81,0.29,7.63,0.12
4,64.18,104.09,2.56,28.07,17.01,11.42,0.09,19.00,138.18,0.17,5.02,0.07
5,72.47,114.84,5.23,23.20,16.59,12.25,0.16,10.55,109.74,0.21,4.71,0.08
...,...,...,...,...,...,...,...,...,...,...,...,...
106143,80.93,174.84,82.96,56.74,139.70,29.32,1.18,9.36,15.96,53.71,51.38,1.30
106144,103.75,217.89,139.58,63.28,181.55,27.56,1.71,11.43,24.75,53.58,55.10,2.29
106145,115.40,225.76,193.19,70.41,213.77,35.25,2.11,10.49,22.11,58.61,61.42,3.20
106146,97.37,179.87,105.12,64.34,169.46,36.24,1.51,6.90,12.55,64.90,62.12,2.16
106147,89.13,179.89,78.47,56.37,134.84,37.98,1.30,8.13,23.21,69.67,66.15,2.42

In [34]:
        y = dataset['AQI_Bucket']
        y

1         1
2         1
3         1
4         1
5         1
         ..
106143    1
106144    2
106145    2
106146    2
106147    2
Name: AQI_Bucket, Length: 10314, dtype: int32

In [35]:
        from sklearn.model_selection import train_test_split
        X_train ,X_test, y_train ,y_test = train_test_split(X ,y ,test_size = 0.3 ,random_state = 1)

In [36]:
        knn = KNeighborsClassifier(leaf_size = 1 ,n_neighbors = 1 ,p = 2)
        knn.fit(X_train ,y_train)
        knn_predict = knn.predict(X_test).reshape(-1, 1)
        #print(classification_report(y_testknn_predict))

In [37]:
        knnAccuracy = round(accuracy_score(knn_predict ,y_test) * 100 ,2)
        kFold = KFold(n_splits = 10, random_state = 10)
        knnCVAccuracy = cross_val_score(knn, X,y ,cv = 10 ,scoring = 'accuracy')
        
        print("The accuracy of K-Nearest Neighbors Classifier is : " ,knnAccuracy)
        print("The cross validated score for K-Nearest Neighbors Classifier is : ",round(knnCVAccuracy.mean() * 100 , 2))

The accuracy of K-Nearest Neighbors Classifier is :  78.29
The cross validated score for K-Nearest Neighbors Classifier is :  67.89

In [38]:
        randomForest = RandomForestClassifier(bootstrap = False,
                                              max_depth = None,
                                              max_features = 'sqrt',
                                              min_samples_leaf = 1,
                                              min_samples_split = 5,
                                              n_estimators = 25)
        randomForest.fit(X_train ,y_train)
        randomForest_predict = randomForest.predict(X_test)

In [39]:
        randomForestAccuracy = round(accuracy_score(randomForest_predict , y_test) * 100 ,2)
        kFold = KFold(n_splits = 10 , random_state = 10)
        randomForestCVAccuracy = cross_val_score(randomForest, X, y ,cv = 10 ,scoring = 'accuracy')
        
        print("The accuracy of Random Forest Classifier is : " ,randomForestAccuracy)
        print("The cross validated score for Random Forest Classifier is : ",round(randomForestCVAccuracy.mean() * 100 ,2))

The accuracy of Random Forest Classifier is :  83.88
The cross validated score for Random Forest Classifier is :  76.74

In [40]:
        logistic = LogisticRegression(C = 545.5594781168514 ,max_iter = 1000 
                                     , penalty = 'l2' ,solver = 'lbfgs')
        logistic.fit(X_train ,y_train)
        logistic_predict = logistic.predict(X_test).reshape(-1, 1)

In [42]:
        #Cross Validation
        logisticAccuracy = round(accuracy_score(logistic_predict ,y_test) * 100, 2)
        kFold = KFold(n_splits = 10, random_state = 10)
        logisticCVAccuracy = cross_val_score(logistic ,X, y, cv = 10, scoring = 'accuracy')
        
        print("The accuracy of logistic regression is : ", logisticAccuracy)
        print("The cross validated score for logistic regression is : " ,round(logisticCVAccuracy.mean() * 100, 2))

The accuracy of logistic regression is :  78.64
The cross validated score for logistic regression is :  74.04

In [45]:
import anvil.server

anvil.server.connect("O37IJ2RCTMDN5SCJKO4OW4PE-QVJCPFLQ6WTY44UQ")

Connecting to wss://anvil.works/uplink
Anvil websocket open
Connected to "Default environment (dev)" as SERVER